version: '3'
services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=dasdassand'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8090:8090"
